services:
  backend:
    container_name: plan-city-backend
    build:
      context: ./Plan-City-Api
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - ./Plan-City-Api/.env

  frontend:
    container_name: plan-city-frontend
    build:
      context: ./Plan-City
      dockerfile: Dockerfile
    ports:
      - "81:5173"
    env_file:
      - ./Plan-City/.env
    volumes:
      - ./Plan-City:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0


    
